-- ==========================================================
-- Consulta : ExcelControlinsumosMostrador
-- Exportado: 2026-10-07 07:17:22
-- ==========================================================

SELECT [Formularios]![Menu Gestion]![semanacontrolimpor] AS Semana, codigolocal() AS Sucursal, FechaDeNumeroDiaSemana([Formularios]![Menu Gestion]![semanacontrolimpor],7) AS FechaInventario, IIf(IsNull([SubReceta]![codporcion]),DLookUp("[Nombre]","[DBIngredientes]","[CodIngrediente]='" & [SubReceta]![CodIngrediente] & "'"),nombreproductocotiprocesado([SubReceta]![codporcion])) AS Producto, IIf(IsNull([SubReceta]![codporcion]),StockIngrediente([SubReceta]![CodIngrediente],[Formularios]![Menu Gestion]![semanacontrolimpor])+StockCotizacion([SubReceta]![CodIngrediente],[Formularios]![Menu Gestion]![semanacontrolimpor]),StockSinProcesar([SubReceta]![codporcion],[Formularios]![Menu Gestion]![semanacontrolimpor])) AS [Inventario Inicial], IIf(IsNull([SubReceta]![codporcion]),IngresoTotalIngrediente([SubReceta]![CodIngrediente],[Formularios]![Menu Gestion]![semanacontrolimpor]),ingresoporcionessemana([SubReceta]![codporcion],[Formularios]![Menu Gestion]![semanacontrolimpor])) AS Ingreso, IIf(IsNull([SubReceta]![codporcion]),MermaIngrediente([SubReceta]![CodIngrediente],[Formularios]![Menu Gestion]![semanacontrolimpor])+MermaCotizacion([SubReceta]![CodIngrediente],[Formularios]![Menu Gestion]![semanacontrolimpor]),MermaUnidadesCotizacion([SubReceta]![codporcion],[Formularios]![Menu Gestion]![semanacontrolimpor])) AS Merma, IIf(IsNull([SubReceta]![codporcion]),StockIngrediente([SubReceta]![CodIngrediente],[Formularios]![Menu Gestion]![semanacontrolimpor]+1)+StockCotizacion([SubReceta]![CodIngrediente],[Formularios]![Menu Gestion]![semanacontrolimpor]+1),StockSinProcesar([SubReceta]![codporcion],[Formularios]![Menu Gestion]![semanacontrolimpor]+1)) AS [Inventario Final], IIf(IsNull([SubReceta]![codporcion]),VentasXTipoNoPorcionSemana([Formularios]![Menu Gestion]![semanacontrolimpor],[SubReceta]![CodIngrediente]),VentasXTipoPorcionSemana([Formularios]![Menu Gestion]![semanacontrolimpor],[SubReceta]![codporcion])) AS Ventas
FROM DBBatidos INNER JOIN SubReceta ON DBBatidos.CodBatido = SubReceta.CodBatido
GROUP BY IIf(IsNull([SubReceta]![codporcion]),DLookUp("[Nombre]","[DBIngredientes]","[CodIngrediente]='" & [SubReceta]![CodIngrediente] & "'"),nombreproductocotiprocesado([SubReceta]![codporcion])), IIf(IsNull([SubReceta]![codporcion]),StockIngrediente([SubReceta]![CodIngrediente],[Formularios]![Menu Gestion]![semanacontrolimpor])+StockCotizacion([SubReceta]![CodIngrediente],[Formularios]![Menu Gestion]![semanacontrolimpor]),StockSinProcesar([SubReceta]![codporcion],[Formularios]![Menu Gestion]![semanacontrolimpor])), IIf(IsNull([SubReceta]![codporcion]),IngresoTotalIngrediente([SubReceta]![CodIngrediente],[Formularios]![Menu Gestion]![semanacontrolimpor]),ingresoporcionessemana([SubReceta]![codporcion],[Formularios]![Menu Gestion]![semanacontrolimpor])), IIf(IsNull([SubReceta]![codporcion]),MermaIngrediente([SubReceta]![CodIngrediente],[Formularios]![Menu Gestion]![semanacontrolimpor])+MermaCotizacion([SubReceta]![CodIngrediente],[Formularios]![Menu Gestion]![semanacontrolimpor]),MermaUnidadesCotizacion([SubReceta]![codporcion],[Formularios]![Menu Gestion]![semanacontrolimpor])), IIf(IsNull([SubReceta]![codporcion]),StockIngrediente([SubReceta]![CodIngrediente],[Formularios]![Menu Gestion]![semanacontrolimpor]+1)+StockCotizacion([SubReceta]![CodIngrediente],[Formularios]![Menu Gestion]![semanacontrolimpor]+1),StockSinProcesar([SubReceta]![codporcion],[Formularios]![Menu Gestion]![semanacontrolimpor]+1)), IIf(IsNull([SubReceta]![codporcion]),VentasXTipoNoPorcionSemana([Formularios]![Menu Gestion]![semanacontrolimpor],[SubReceta]![CodIngrediente]),VentasXTipoPorcionSemana([Formularios]![Menu Gestion]![semanacontrolimpor],[SubReceta]![codporcion])), DBBatidos.Marca, DLookUp("[PaquetePorciones]","[Cotizaciones]","[CodCotizacion]=" & CotiPrincipalProdCompraVenta([DBBatidos]![CodBatido])), DBBatidos.CodGrupo, DBBatidos.Vigencia, SubReceta.InsumoClave, CotiPrincipalProdCompraVenta([DBBatidos]![CodBatido]), SubReceta.codporcion, SubReceta.CodIngrediente
HAVING (((DBBatidos.CodGrupo)=7) AND ((DBBatidos.Vigencia)=True) AND ((SubReceta.InsumoClave)=True))
ORDER BY DBBatidos.Marca, DLookUp("[PaquetePorciones]","[Cotizaciones]","[CodCotizacion]=" & CotiPrincipalProdCompraVenta([DBBatidos]![CodBatido]));

